apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: 'https://kubernetes.default.svc'
    - name: in-cluster
      namespace: nodejs-demo
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/ingoldooo/argocd-oc.git'
status: {}
