apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs
  namespace: argocd
spec:
  destination:
    namespace: nodejs-demo
    server: 'https://kubernetes.default.svc'
  project: nodejs-app
  source:
    path: ./Helm
    repoURL: https://github.com/ingoldooo/argocd-oc.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
